<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Главная - Система тестирования</h1>
<div>
    <form action="/reg" method="post">
        <input type="submit" value="Регистрация">
    </form>

    <br>
    <form action="/entrance" method="post">
    <input type="submit" value="Вход">
    </form>
</div>

</body>
</html>

