<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div>
    <h1>Восстановление пароля</h1>
    <br>
    <h2>Инструкция по восстановлению пароля направлена на Ваш e-mail</h2>
    <form action="/signIn" method="post">
        <input type="submit" value="Перейти на страницу авторизации">
    </form>
</div>

</body>
</html>