<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<div>
    <h1>Восстановление пароля</h1>
    <br>
    <form action="/afterRecovery" method="post">
        <input name="login" placeholder="email">
        <br>
        <input type="submit" value="Сбросить пароль">
    </form>
</div>

</body>
</html>